export default {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: 'Gumroad',
      href: 'https://hppedeaf.gumroad.com/l/CameraAnimationHppe',
    },
  ],
};